
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_oauth2
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://auth.localhost:9000/oauth/token_key

server:
  port: 9002

logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
